# Uncomment the next line to define a global platform for your project
platform :ios, '13.5'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'SharedCode', :path => '../../SharedCode'

end
